text/0001-frontend-disable-prod.md

takes over https://github.com/meilisearch/specifications/pull/8

Remove frontend in production

---

text/0042-paginated-search.md
text/xxxx-paginated-search.md

Initialize specification for finite pagination on the search API endpoint.

Paginated Search

---

text/0043-phrase-query.md
text/xxxx-phrase-query.md

Initialize Phrase Query specification

Phrase Query

---

text/0036-exactness-criterion.md
text/xxxx-exactness-criterion.md

Initialize exactness-criterion specification

Exactness Criterion

---

text/0039-_formatted-field-behavior.md
text/xxxx-_formatted-field-behavior.md

Initialize _formatted field behavior specification.

_formatted Field Behavior

---

text/0034-telemetry-policies.md
text/xxxx-telemetry-policies

Initialize specification for our analytics policy.

Analytics Policy

---

open-api.yaml
text/0055-sort.md

- ✨ [Sort at search-time](text/0055-sort.md)

Release v0.22

---

text/0061-error-format-and-definitions.md

@meilisearch/docs-team We have added an error missing from the specification.

Patch error format and messages

---

text/0034-telemetry-policies.md

This specification describes an exhaustive list of anonymous metrics collected by the MeiliSearch binary. It also describes the tools we use for this collection and how we identify a Meilisearch instance.
At MeiliSearch, our vision is to provide an easy-to-use search solution that meets the essential needs of our users. At all times, we strive to understand our users better and meet their expectations in the best possible way.
Although we can gather needs and understand our users through several channels such as Github, Slack, surveys, interviews, or roadmap votes, we realize that this is not enough to have a complete view of MeiliSearch usage and features adoption. By cross-referencing our product discovery phases with aggregated quantitative data, we want to make the product much better …

Rework Analytics Stack

---

.github/workflows/bump.yml
open-api.yaml
text/0034-telemetry-policies.md
text/0061-error-format-and-definitions.md
text/0077-words-position-limit.md

- [Rework error format and enhance messages](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md)
- [Remove the limit of 1000 positions per attribute](https://github.com/meilisearch/specifications/blob/develop/text/0077-words-position-limit.md)
- [Rework the analytics stack](https://github.com/meilisearch/specifications/blob/develop/text/0034-telemetry-policies.md)
- [Fix Open API documentation of search sort query param for GET/POST search route](https://github.com/meilisearch/specifications/pull/91)
@paulRbr

Release v0.24.0

---

open-api.yaml
text/0085-api-keys.md

Rename API Key action `indexes.add` to `indexes.create`

---

text/0034-telemetry-policies.md

Checked with @gmourier: @brunoocasali, we need to adapt with the rebranding :)

Update the integration analytics following the rebranding

---

text/0105-dumps-api.md

This PR adds the missing information regarding the dump version support.
Also, makes consistent the numeric titles.
@meilisearch/docs-team FYI 😇 Nothing to add on your side, just to let you know the information are here.

Dump support

---

text/0059-geo-search.md
text/0061-error-format-and-definitions.md

update ranking rules error message to return lowercased rules.

Misc - Update `invalid_ranking_rule` error message

---

text/0001-script-based-tokenizer.md

Change tokenizer old spec to fit the new Charabia implementation.
---
- Update `text/0001-script-based-tokenizer.md`
N/A
---
N/A

Tokenizer - Update specification to fit Charabia implementation

---

README.md

Rewrites and simplifies the readme to bring it up to date with the [new specification writing and release process](https://www.notion.so/meilisearch/Specification-process-b017a397baaf492c9bc375bcca7ca4c6).

Update Specification Workflow

---

text/0060-tasks-api.md

Adds in the technical details section the prioritization order of the task types.
---
See the Summary section.
N/A
---
N/A
---
N/A

Tasks API - Add task priority order section

---

text/0055-sort.md

related to https://github.com/meilisearch/meilisearch/pull/3749

Update sort Error message

---

open-api.yaml
text/0034-telemetry-policies.md
text/0061-error-format-and-definitions.md
text/0085-api-keys.md
text/0118-search-api.md
text/0174-metrics-api.md
text/0193-experimental-features.md
text/0194-experimental-feature-api.md
text/0195-ranking-score.md

---
Specify the new experimental feature API.
---
- Add new spec that was missing on experimental features in general, listing all the experimental features
- Add new spec on the experimental feature API
- Update open API
N/A
---
N/A
---

Experimental features

---

text/0246-facet-search-api.md

---
_Explain with a few sentences the goal of the specification_
---
_Explain in a clear way the changes bring by the specification; Bullet points FTW;_
_Explain in clear way subjects that are out of scope and shouldn't be discussed by the reviewers_
---
_Explain clearly what reviewers should specifically look for to facilitate the review phase. Also, mention the sections that will not necessarily be taken into account if reviewed._
---

fix: set valid links for facetName errors

---

text/0034-telemetry-policies.md
text/0123-proximity-precision.md
text/0123-settings-api.md

Define the `proximityPrecision` setting.
---
- Add a new file with the setting details
- modify the global index setting spec
- modify the telemetry spec

Add proximity precision setting

---

open-api.yaml
text/0034-telemetry-policies.md
text/0119-instance-options.md
text/0123-proximity-precision.md
text/0123-settings-api.md
text/0262-task-queue-webhook.md

Release v1.6.0
