meilisearch/specifications

text/0048-rename-max-mdb-size-var.md

This specification is written to rename the `MAX_MDB_SIZE` environnement variable and `--max-mdb-size` option flag to `MAX_INDEX_SIZE` and `--max-index-size`.
Since version 0.21 no longer has a main LMDB database for all indexes but one LMBD database per index, the concept of a `main` database no longer exists internally.

Rename MAX_MDB_SIZE env var and --max-mdb-size option flag

---

text/0047-reset-stop-words-synonyms-settings-with-null.md

All Sub Settings `POST` endpoint accepts a null value in the http request body to reset the engine configuration to the default values. This is not the case for [Stop-words](https://docs.meilisearch.com/reference/api/stop_words.html#update-stop-words) and [Synonyms](https://docs.meilisearch.com/reference/api/synonyms.html#update-synonyms) settings endpoints.
This specification is written to make the above mentioned routes consistent with the others.

Reset Stop-Words and Synonyms Settings With A Null Value

---

open-api.yaml

In the route `/version` the `buildDate` is now named `commitDate` and the format has changed

Change the /version response

---

text/0055-sort.md

- In the case where an attribute is specified as a sort criterion at search time and if this attribute is of a different type between several documents, the numeric type will always be favored first by the engine. This means that documents with numeric values for this attribute will be sorted before those with string values. This can lead to awkward sorting behavior, so the user should make sure to have the same type on the attribute he wants to sort on for all these documents.
- In the case where an attribute is specified as a sort criterion at search time and does not exist on a document, the document will be placed at the end of the ranking rule sort.

Add definitions of the missing behaviors for the sort specification

---

text/0059-geo-search.md

As imagined during the first phases of discovery we encounter a technical difficulty to compute a descending order around a `_geoPoint`.
The technical team will have to do some preparatory work to overcome this limitation. For the time being, it is not planned to spend more time on this as it is not a primary use case. The impact may be very small, so it's not worth the effort at this point.
It was decided after a discussion with @irevoire and @Kerollmops that when the user specifies the sort rule `_geoPoint(lat, lng):desc` an error `invalid_sort` will be returned with a message explaining that `:desc` is not available.
To keep consistency and not to introduce a different syntax among the `sort` search parameter. This is something we'll re-evaluate later.

Patch GeoSearch specification to mention technical limit on `desc` ordering around a _geoPoint

---

text/0028-indexing-csv.md
text/0029-indexing-ndjson.md

On closer inspection, the previous error definitions for the first iteration of the specifications are insufficient.
This patch adds a more detailed error definitions concerning `content-type` and request body payload for POST/PUT routes for the `indexes/:index_uid/documents` endpoint

Patch error codes for csv and ndjson formats specs

---

text/0055-sort.md

Added this case to guide the user if the `sort` ranking rule is not specified in the ranking rules.

Add error at search time if the `sort` ranking rule is not specified in the ranking rules.

---

text/0059-geo-search.md

- Add an alternative message for `invalid_sort` and `invalid_filter` errors to handle reserved keywords.
- `invalid_criterion` is renamed to `invalid_ranking_rule` and add an alternative message to handle reserved keywords.
- Update `invalid_geo_field` error message.
Pinging @guimachiavelli for information sharing.

Add alternative message for reserved keyword and update invalid_criterion error definition

---

text/0055-sort.md

- `sort` ranking rule is moved after the `attribute` ranking rule to promote a more relevant sort by default.

Put `sort` ranking rule in a position that promote relevancy by default

---

text/0059-geo-search.md

Thanks, @irevoire ✨
- Handling distance in other formats (like the imperial format). **It's easy to implement on the user side though.**
- Handling position in other formats. It seems that [degrees and minutes](https://www.pacioos.hawaii.edu/voyager-news/lat-long-formats/) are also used a lot. **It's easy to implement on the user side though.**

Patch GeoSearch Future Possibilities

---

text/0059-geo-search.md

We were able to find a solution to implement sorting around a `_geoPoint` in descending order. 
The specification is updated to remove the mention of this initial limitation.
@meilisearch/docs-team FYI

Patch GeoSearch specification to add descending order capability to _geoPoint built-in sort

---

.github/workflows/bump.yml
open-api.yaml
text/0060-refashion-updates-apis.md

The term `update` is not the best choice as it can be confused with `document` or `setting` updates. We have chosen to replace this term with `task`, which is more generic and better reflects the meaning of this API resource.
As an additional change, we have reworked the format of an update to make it more in line with our expectations of an API that is supposed to be easily understandable and developer-oriented.
The changes we will make to the response format of the `task` object lists will make it easier to add more functionality in a future iteration. See the Future Possibilities section for a brief overview.
Two new API endpoints are added. Although quite simple, they allow consulting the list of tasks or a specific task without being forced to know the related index.
- The `update` …

Refashion Update APIs

---

text/0059-geo-search.md

Improve understanding of the functionality through the use of precise error messages.

Add message variants for geosearch `invalid_filter` and `invalid_sort` errors

---

open-api.yaml

It seems there's a missing empty line to differentiate two call-outs in the documentation of the `sort` query parameter of the `GET` search route.
Strangely enough, the `POST` search route doesn't have this `info` call-out maybe it's an oversight?
Fixes a documentation visual defect in the OpenAPI contract [here](https://bump.sh/doc/meilisearch#get-indexes-parameter-search-sort).

Fix documentation of search `sort` query param

---

text/0060-refashion-updates-apis.md

We have the possibility to add more information than initially planned. We propose to add essentially a diff detail for tasks that are supposed to receive documents and finally index some or all of them. `documentsAddition` / `documentsPartial` / `documentsDeletion`.
We also specify which `primaryKey` is sent for index creation and update if it is filled in.
For `settingsUpdate` task type, the `details` field does not change.
Deleting an index means that tasks for that index can no longer be found via `indexes/:indexName/tasks`. However, they are still accessible via `/tasks` for this version.

Add `details` payload by task type and index deletion behavior on task retrieval

---

text/0034-telemetry-policies.md

Describes the events and associated metrics to [measure the usage of the new API routes `tasks`](https://github.com/meilisearch/specifications/blob/develop/text/0060-refashion-updates-apis.md#i-measuring)
@meilisearch/docs-team 🔍

Update telemetry policies for new task endpoints

---

text/0060-refashion-updates-apis.md

Corrects naming and clarifies some information.
Does not impact the @meilisearch/core-team nor the @meilisearch/docs-team.

Patch Task specification for `details` part.

---

text/0034-telemetry-policies.md

The segment identify call is only sent after the first hour if the instance is still running. At the first launch, MeiliSearch sends a `Launched` event on an instance ID equal to `total_launch` in order to avoid tracking instances usage for nothing when they could be shut down and never restarted.

Add technical detail about the first Launched event and the segment identify call

---

text/0034-telemetry-policies.md

Replace `q.avg_terms_number` by `q.max_terms_number`.
@meilisearch/docs-team: A slight change to come with v0.25.0 concerning telemetry for the search `q` parameter.

Replace q.avg_terms_number by q.max_terms_number in telemetry spec

---

text/0060-refashion-updates-apis.md

The naming of task types is updated to be corrected. Seen with @dichotommy 🤓
@meilisearch/docs-team 👋

Patch `task` `type` enum naming

---

text/0061-error-format-and-definitions.md

As the index management is now asynchronous. We take the opportunity to update the information of an error if it is asynchronous, synchronous, or both.
@MarinPostma, on the part of the so-called internal errors I'm really not sure. Don't hesitate to make a pass and adjust the synchronicity label if it is wrong. 🙏

Patch Async/Sync part of errors definition

---

text/0028-indexing-csv.md

Consider empty cell in a CSV payload as `null` value at indexing.
- If a field is of type `string`, then an empty cell is considered as a `null` value (e.g. `,,`), anything other is turned into a string value (e.g. `, ,` is a single whitespace string)
- If a field is of type `number`, when the trimmed field is empty, it's considered as a `null` value (e.g. `,,` `, ,`); otherwise Meilisearch try to parse the number.
Given the CSV payload
```
id:number,label,price:number,colors
1,t-shirt,,red
```
the search result should be displayed as
```json
{
"hits": [
{
"id": 1,
"label": "t-shirt",
"price": null,
"colors": "red"
}
],
...
}
```

Handle empty cell as `null` value for CSV format

---

text/0061-error-format-and-definitions.md

Following feedback on https://github.com/meilisearch/product/discussions/319. 
MeiliSearch does not return an error to guide the user anymore when a payload with 0 documents is sent for the routes `POST`- `PUT` `/documents`.
This is to facilitate the creation of an empty index and the use of message queues sending empty payloads to be indexed.

Accepts 0 documents payload on `POST`/`PUT`- `/documents`

---

text/0000-specification-template.md

I update the template of the specs according to our current usage
- I remove the Meilisearch tracking issue part since sometimes multiples issues are related (with the improvements of the spec for example). However, if this is something you want to keep back in the process, please let me know
- I simplified the titles so that it's more adapted to what we do at the moment.
Since we are still learning about managing specs, I think this is important to provide a user-friendly format first adapted to our current usage, and make it improve as we go along. Complexity is not our friend at our stage from my POV 🤓 
Let me know if you want me to add something else 😇

Update spec template according to our current usage

---

text/0124-documents-api.md

This specification describes the documents API endpoints permitting to list, fetch, add/replace, and delete index documents.
This is a necessary specification to start work on v0.28.

Documents API

---

text/0061-error-format-and-definitions.md

Add a variant for `invalid_filter` and `invalid_sort` errors when `filterablesAttributes` / `sortablesAttributes` are empty.

Errors - Add variant for `invalid_filter`/`invalid_sort` when related settings are empty

---

text/0118-search-api.md

Following our discusssion @gmourier, @irevoire, @bidoubiwa, I tried to make the `_formatted` behavior clearer.
Is it the case for you?

Improve formatted spec

---

text/0034-telemetry-policies.md

Following this [comment](https://github.com/meilisearch/integration-guides/issues/150#issuecomment-966360488) pointing out that some browsers forbid the customization of the User-Agent header, the analytics stack can now take the value of a `x-meilisearch-client` query parameter if found instead of the user-agent header to track the usage of our SDKs/Integrations.

Telemetry - Add `x-meilisearch-client` query parameter

---

open-api.yaml
text/0060-tasks-api.md

🤖 [API Diff](https://github.com/meilisearch/specifications/pull/144#issuecomment-1104996509)
Following this [discussion](https://github.com/meilisearch/product/issues/368#issuecomment-1104900879), we decided to rename the `uid` field in a summarized task response (202 Accepted) to `taskUid` to bring more context and help understanding what is given as a response.
- `uid` contained in 202 Accepted (Summarized Task Response) is renamed to `taskUid`

Tasks API - Rename `uid` to `taskUid` in the `202 - Accepted` Summarized Task Response

---

open-api.yaml
text/0060-tasks-api.md

🤖 [API Diff](https://github.com/meilisearch/specifications/pull/115#issuecomment-1129027036)
`task` resource lists now support seek pagination, allowing users to browse multiple sets of `task` items.
- Add `limit`, `from`, `next` response attributes to task list response.
- It only concerns the `/tasks` endpoint. `/indexes/:uid/tasks` endpoint is removed by https://github.com/meilisearch/specifications/pull/116.
Following the specification aiming to stabilize the `task` API resource, we want to give Meilisearch capabilities to adapt to many use-cases, thus involving unpredictable orders of magnitude regarding `task` growth over time.
This feature should be usable by both solo developers and technical teams.
The objectives set during the discovery's exploration phase for the pagination of …

Tasks API - Seek/Keyset based pagination

---

open-api.yaml
text/0034-telemetry-policies.md
text/0060-tasks-api.md
text/0061-error-format-and-definitions.md

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/116#issuecomment-1105255632)
Add filtering capabilities to the `tasks` endpoints to facilitate the management of an instance and its indexes, or a specific index.
This first iteration adds filters on the `status`, `type` and `indexUid` attributes of the `task` API resource.
- Add filtering capabilities on `type`, `status` and `indexUid` for `GET` `task` lists endpoints.
- It is possible to specify several values for a filter using the `,` character. e.g. `?status=enqueued,processing`
- Between two different filters, an AND operation is applied. e.g. `?status=enqueued&type=indexCreation` is equivalent to `status=enqueued AND type = indexCreation`
- `GET /indexes/:indexUid/tasks` is removed
- It can be replaced by `GET …

Tasks API - Filter tasks list by `type`/`status`/`indexUid`

---

open-api.yaml
text/0085-api-keys.md
text/0124-documents-api.md
text/0132-indexes-api.md

🤖 [API Diff](https://github.com/meilisearch/specifications/pull/138#issuecomment-1090115742)
In order to stabilize the APIs around a convention, we add resources under a `results` array when they can be listed. 
This is already the case for the `tasks` and `API Keys` resources which have made this change along the way.
The `/search` endpoints are not affected by these changes but this can be reconsidered with caution. `hits` seem to be effective and changing it would cause a big breaking change. `hits` is already well established in the market e.g. elasticsearch, algolia, typesense.
The stats API is not concerned for the moment and maybe concerned later given feedback and what it could become. The idea behind it is that this resource does not only return index statistics but also more …

API Guideline - Return list of API resources under a `results` array

---

open-api.yaml
text/0124-documents-api.md

🤖 [API Diff](url)
The documents API is used to manage documents within an index.
`displayedAttributes` allows limiting the attributes that can be retrieved in the search but also impacts the endpoints of the documents API.
My proposal is to remove this behavior from the documents API. Indeed, in order to manage a Meilisearch instance, it is good to have all the information about it.
Today, it implies the user to modify `displayedAttributes` to access all the information which will also impact the search. This is not desirable for the developer experience.
---
Following this [discussion ](https://github.com/meilisearch/product/discussions/440)
`attributesToRetrieve` query parameter is renamed to `fields` on this API. Using a more generic name that does not collide with …

Documents API - `displayedAttributes` should not impact the documents API / Rename `attributesToRetrieve` to `fields`

---

text/0059-geo-search.md
text/0061-error-format-and-definitions.md

It’s also important to note that the first error message could not stay the same (and show the whole object) as before because we lost this information with the v0.27 and the nested fields 😢

Geosearch - Enhance lat/lng format error messages

---

text/0034-telemetry-policies.md

Following #145, the core team had some technical difficulties implementing it.
We decided to replace the `x-meilisearch-client` query parameter with a custom header.
According to our exploration, a custom header is rarely stripped by a proxy by default (_tested on nginx_). If it still happens, the analytics will just not be collected in this case.
We found this solution to be the least impactful regarding the user experience while ensuring that it can be implemented quickly without rewriting how the API passes an `x-meilisearch-client` query parameter for a non-business field to the end-user POV.

Telemetry - Replace `x-meilisearch-client` query parameter by `X-Meilisearch-Client` header

---

text/0105-dumps-api.md

Update the dump table accordingly to the new dump version: https://github.com/meilisearch/meilisearch/issues/2430

Misc — Update dump versions compatibility table

---

text/0061-error-format-and-definitions.md

Add variants to help users when the `_geo` field is invalid.
- Add a variant in the case the provided `_geo` is not an object.
- Add a variant in the case `_geo.lat` **and** `_geo.lng` fields are missing. 
---
- Update `text/0061-error-format-and-definitions.md` to add two new variants for `invalid_geo_field` error.
N/A
---
N/A
---
Implemented in https://github.com/meilisearch/milli/pull/561

Geosearch - Add error variants for `invalid_geo_field` error

---

open-api.yaml
text/0034-telemetry-policies.md
text/0060-tasks-api.md
text/0096-auto-batching.md
text/0119-instance-options.md

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/162#issuecomment-1219280272)
---
_Following https://github.com/meilisearch/meilisearch/issues/2582_
Enables auto batching by default and removes unnecessary options.
---
- Auto-batching is now activated by default. It involves the `--enable-auto-batching` flag being removed and replaced by `--disable-auto-batching`. An environment variable should also be added to handle this option (`MEILI_DISABLE_AUTO_BATCHING`)
- Remove all the current options: `--debounce-duration-sec`, `--max-batch-size` and `--max-documents-per-batch`.
- Remove the `batchUid` field in task object; It's now an internal field not being displayed.
N/A
---
N/A
---

Auto-batching - Enable feature by default and remove unwanted options

---

text/0118-search-api.md

With the release of Meilisearch v0.29.0, we hope to add more filter operators and to change the behaviour of `NOT` and `!=`. This PR updates the specification so that it is up-to-date with these changes. I have also updated it to be more precise and complete.
---
- Update `search-api.md`
N/A
---
I am not entirely sure what the expected style of the spec is supposed to be, so please let me know if something can be slightly improved or if it is completely wrong :)
---
N/A

Search API — Filters - Introduce IN and EXISTS and describe filter capabilities in more precisely

---

text/0034-telemetry-policies.md

Add `Stats Seen` event to the telemetry policies specification.
---
- Add `Stats Seen` event
-  `user_agent`:  Represents the user-agent encountered on this call
- `per_index_uid`: `true` if an uid is used to fetch an index stat resource, otherwise `false`
n/a
---
n/a
---

Telemetry - Add `Stats Seen` event

---

open-api.yaml

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/170#issuecomment-1218049975)
---
Add examples components for each summarized task type to make it more precise for the reader and up-to-date with the past changes.
Related to: #141 
---
n/a
n/a
---
n/a
---

Misc — Add examples components for each summarized task type

---

text/0172-health-api.md

Catch up on missing spec for the `/health` endpoint.
---
- Add `0172-health-api.md` specification file
n/a
---
n/a

Health API — Catch up

---

open-api.yaml
text/0034-telemetry-policies.md
text/0118-search-api.md

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/173#issuecomment-1222297686)
---
Implement the ability to choose a word matching strategy at search time between `last` and `all` strategies.
We know that some users are still stuck in pre-v0.21 versions because of the hard implementation of the `last` mode introduced with v0.21. We are confident that adding the `all` strategy will permit those users to move to the newer versions while giving more versatility to Meilisearch regarding relevancy tweaking.
---
- Add a `matchingStrategy` parameter to POST and GET `search` endpoints
- `last` is the default strategy if the field is not specified
- 2 strategies are available: `last` and `all`.
- `most_used_matching_strategy` is added as a telemetry node on POST and GET `/search` …

Search API — Add `matchingStrategy` parameter with `last` / `all` strategies

---

text/0124-documents-api.md
text/0135-indexing-json.md

Add a catch-up specification to describe the indexing of JSON documents.
---
- Add `indexing-json.md`
- Update `documents-api.md`
N/A
---
N/A

Documents API — Indexing json

---

open-api.yaml
text/0001-script-based-tokenizer.md
text/0034-telemetry-policies.md
text/0060-tasks-api.md
text/0061-error-format-and-definitions.md
text/0096-auto-batching.md
text/0118-search-api.md
text/0119-instance-options.md
text/0124-documents-api.md
text/0132-indexes-api.md
text/0135-indexing-json.md
text/0136-documents-soft-deletion.md
text/0171-version-api.md
text/0172-health-api.md

- #159
- #161
- #162 
- #163
- #164
- #165
- #168
- #169
- #170
- #171
- #172
- #173
- #167

Release v0.29.0

---

.github/workflows/bump.yml

Specification workflow now starts from the main branch or a release branch. `develop` should not be needed anymore.

GitHub Actions - Trigger OpenAPI Diff on `release-v*` branches

---

text/0061-error-format-and-definitions.md
text/0085-api-keys.md

Following this discussion: https://github.com/meilisearch/product/discussions/552
Indicate to users that a master key must first be defined when launching Meilisearch to access the API Keys management feature.
---
- Add a new error: `missing_master_key`
- Update the API Keys specification
---
N/A

Keys API - Indicate to users that a master key must be set at Meilisearch launch to use that feature 

---

text/0061-error-format-and-definitions.md

Use the `invalid_index_uid` error message as a variant for `invalid_api_key_indexes` error when an invalid index uid is set into the API Key `indexes` field.
https://github.com/meilisearch/meilisearch/issues/2158
https://github.com/meilisearch/meilisearch/issues/2924

Keys API - Add a variant message when an index uid format is invalid for the indexes field.

---

text/0119-instance-options.md

Replace `127.0.0.1:7700` by `localhost:7700` to match both ipv4 and ipv6 address.
Related to:
- https://github.com/meilisearch/meilisearch/issues/2782
- https://github.com/meilisearch/meilisearch/pull/2861
---
See Summary section.
N/A
---
N/A
---
N/A

Instance Options - `localhost:7700` instead of `127.0.0.1:7700`

---

text/0034-telemetry-policies.md
text/0119-instance-options.md
text/0185-configuration-file.md

Meilisearch options can be defined in a `.toml` configuration file being loaded at launch.
Teams can easily version, track, and share configuration files. It makes it easier to learn about the different options available and to define at a glance how Meilisearch is configured.
A default config file is defined as `config.toml` and is retrieved by Meilisearch by default in its current working directory.
The current consistency rule is that all environment variables and launch options are configurable by a dedicated key in the configuration file.
Configuration keys are named following the `snake_case` convention from the name of a CLI option. That is, `--import-dump` must be named `import_dump` within the configuration file.
There is an exception rule. The `config_file_path` key is not …

Configuration File Support

---

text/0119-instance-options.md

Precise that `--max-index-size` is for an index and not all indexes.
Related to https://github.com/meilisearch/product/issues/530
---
See Summary Section.
N/A
---
N/A
---
N/A

Instance Options - Precise that `--max-index-size` is for an index and not all indexes.

---

open-api.yaml
text/0034-telemetry-policies.md
text/0118-search-api.md

🤖  [API Diff](https://bump.sh/doc/meilisearch/changes/468c7f4f-2594-4bdf-8b8d-dc454499b776)
---
This specification introduces a new pagination system as an alternative to the `offset`/`limit`. This pagination component can be used to navigate search results via a page selection.
---
Previously, the only way to paginate over the search results was by using `limit` and `offset` which returned both these fields an `estimatedTotalHits`. 
This feature introduces two new query parameters `page` and `hitsPerPage` that lets you paginate over pages more easily. They add 4 new response fields: `page`, `hitsPerPage`, `totalPages` and `totalHits`.
When one system is used, only the fields of that pagination system are present in the response object.
When multiple fields from different pagination …

Search API - Page Selection Component

---

text/0105-dumps-api.md

Simplify the `dump version` section since after https://github.com/meilisearch/meilisearch/pull/3170 all dumps version can be imported in Meilisearch (> v0.30).
Related to: https://github.com/meilisearch/meilisearch/issues/2985
---
- Removed the "Highest compatibility dump version" column since all dumps will be compatible with Meilisearch v1.0
N/A
---
N/A
---

Simplify dump version section since v1.0 can import all dumps

---

open-api.yaml
text/0034-telemetry-policies.md
text/0105-dumps-api.md
text/0119-instance-options.md

---
Propagate the changes of https://github.com/meilisearch/meilisearch/pull/3175
---
- uses of `dumps foo` as a compound noun are replaced by `dump foo`
- `infos.dumps_dir` property is renamed `infos.dump_dir`
N/A
---
- I did not update the link to the website: https://docs.meilisearch.com/reference/features/configuration.html#dumps-destination, we could want `dump-destination` as the header here, and this might be inconsistent with me renaming that header in the spec itself (`3.3.6. Dump destination` in `text/0119-instance-options.md`
---
- [] Update telemetry datapoints _(if needed; Apply the …

 Rename dump command from `--dumps-dir` to `--dump-dir`

---

text/0136-documents-soft-deletion.md

No API change
---
Update the functional specification of soft-deleted documents after https://github.com/meilisearch/milli/pull/747
Related to https://github.com/meilisearch/meilisearch/issues/3231
---
- Fixed some typos
- Change the functional specification to reflect the recent changes to the implementation that will be effective in v1
N/A
---
N/A
---

Update the specification of soft-deleted documents

---

text/0034-telemetry-policies.md
text/0060-tasks-api.md
text/0119-instance-options.md

No API change
---
Update specification after removal of the `--max-index-size` and `--max-task-db-size` flags as per https://github.com/meilisearch/meilisearch/issues/3231
---
- update CLI arguments to account for removed flags
- renumber a lot of sections as a result
- The soft-deleted documents still reference the removed flags in this PR. This change is covered in #206.
---
N/A
---

Remove `--max-index-size` and `--max-task-db-size`

---

text/0061-error-format-and-definitions.md

No API changes
---
Update the errors that can be returned when inference fails following the changes made in https://github.com/meilisearch/meilisearch/pull/3269.
Related to https://github.com/meilisearch/meilisearch/issues/3233.
---
- Replace `primary_key_inference_failed` with `primary_key_no_candidate_found` and `primary_key_multiple_candidates_found`.
N/A
---
N/A
---

Robustify Primary Key Inference - Update related errors

---

text/0105-dumps-api.md

Update the spec following this issue: https://github.com/meilisearch/meilisearch/issues/3250
The previous old error was missing in the spec

Add error message when doing a migration

---

text/0060-tasks-api.md

https://github.com/meilisearch/meilisearch/issues/3342
Specify the effect of the `*` value when used in the task filters.
Specify the effect of the `*` value when used in the task filters.
I specified the effect of the `*` value when used in the task filters.

Specify the effect of the `*` value when used in the task filters

---

open-api.yaml
text/0028-indexing-csv.md
text/0061-error-format-and-definitions.md

Specify the usage of the new query parameter `csvDelimiter` that lets you customize the csv delimiter you wants to use in your document addition.
---
Added the `primaryKey` in the OpenAPI schema as a catch up
---
- Implemented in https://github.com/meilisearch/meilisearch/pull/3505

Documents API — Support a csv delimiter customization

---

text/0059-geo-search.md

Add a simple sentence on the fact that `null` is a valid geo field value and won't throw an error.
Implemented in https://github.com/meilisearch/meilisearch/pull/3515

Geosearch — Accept `null` for the `_geo` field

---

text/0132-indexes-api.md

- In v1.1, changes were made to how we open indexes so that we can open an arbitrary number of indexes of almost arbitrary size.
- This PR specifies the new behavior of index wrt size/count.
---
- Augment indexes API text with indication on the limits and behavior of index wrt size/count in the technical details
N/A
---
N/A
---

Add small blurb about index count / max size

---

text/0028-indexing-csv.md

Add support for the boolean type in csv
e.g `isActive:boolean` as the column name:type to interpret `true`/`false` values as boolean and not string
Associated issue: https://github.com/meilisearch/meilisearch/issues/3572
Implemented in: https://github.com/meilisearch/meilisearch/pull/3576

CSV Content-Type — Add support for the boolean type in CSV

---

text/0118-search-api.md

This PR is updating the search API specification and, specifically the filter field. It explains the support of the `IS NULL` and `IS EMPTY` operators. [The original PR](https://github.com/meilisearch/meilisearch/pull/3571) is available on GitHub, and [the original product discussion](https://github.com/meilisearch/product/discussions/539) too!
- Explain the `IS EMPTY` operator on the filter field of  the search API
- Explain the `IS NULL` operator on the filter field of  the search API
_Explain clearly what reviewers should specifically look for to facilitate the review phase. Also, mention the sections that will not necessarily be taken into account if reviewed._
---
- [] ~Update OpenAPI specification file _(if needed; Apply the `OpenApi` label)_~
- [] ~Update telemetry datapoints _(if …

Filter operators - `IS NULL` and `IS EMPTY` filter operators

---

text/0060-tasks-api.md

Specify the auto-deletion of tasks that was introduced in meilisearch v1.2
Associated issue: https://github.com/meilisearch/meilisearch/issues/3622
Implemented in: https://github.com/meilisearch/meilisearch/pull/3693

Auto deletion of tasks

---

open-api.yaml
text/0061-error-format-and-definitions.md

Update payload_size_too_large error related to https://github.com/meilisearch/meilisearch/pull/3739
---
```diff
{
-    "message": "The provided payload reached the size limit.",
+    "message": "The provided payload reached the size limit. The maximum accepted payload size is :playloadSizeLimit.",
"code": "payload_too_large",
"type": "invalid_request",
"link": "https://docs.meilisearch.com/errors#payload_too_large"
}
```

Update `payload_too_large` error `message`

---

open-api.yaml
text/0034-telemetry-policies.md
text/157-faceting-setting-api.md

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/247#issuecomment-1606888158)
---
Describes the new index setting that gives the ability to customize a facet sort order
---
N/A
---
N/A
---

Faceting Setting API - sortFacetValuesBy 

---

open-api.yaml
text/0034-telemetry-policies.md
text/0061-error-format-and-definitions.md
text/0118-search-api.md
text/0124-documents-api.md

🤖  [API Diff](https://github.com/meilisearch/specifications/pull/248#issuecomment-1609060852)
---
Describes the experimental vector search related properties and capabilities
---
- Introduces `vector` and `_semanticScore` properties on `search-api.md`
- Introduces the special properties `_vectors` for a document body
- Describes related errors
- `invalid_search_vector`
- `invalid_document_vectors_field`
- Add the experimental properties on open-api.yaml
- Describes added telemetry
N/A
---
N/A
---

Vector Search - `EXPERIMENTAL`

---

open-api.yaml
text/0034-telemetry-policies.md
text/0118-search-api.md
text/0195-ranking-score.md

---
Specify the ranking score and ranking score details.
Specification for https://github.com/meilisearch/meilisearch/issues/3771
---
- Add new ranking score specification
- Update search API with the new query parameters and the new fields added to returned documents
- Update telemetry
- Update Open API
N/A
---
- This PR references the "experimental features" spec, and so is based on the `experimental_features` branch rather than the `release-v1.3.0` branch. **When merging**, make sure to merge #250 before this PR.
---

Score details

---

open-api.yaml
text/0060-tasks-api.md

As [we recently added the `total` field on the `/tasks` route](https://github.com/meilisearch/meilisearch/pull/3889) I update the specifications accordingly. The `total` field exposes the total number of tasks matching the given tasks filter/query.

Tasks route total

---

open-api.yaml
text/0174-metrics-api.md

---
Implemented in https://github.com/meilisearch/meilisearch/pull/3789
- Prefix all the metrics by `meilisearch` so they're easier to find
- Add the real database size used by meilisearch
- Add metrics on the task queue
- Add the `meilisearch_last_update` and `meilisearch_is_indexing` introduced in https://github.com/meilisearch/meilisearch/issues/3843

Document the latest metrics improvements

---

open-api.yaml
text/0034-telemetry-policies.md
text/0061-error-format-and-definitions.md
text/0118-search-api.md

Update specifications related to the [Define fields to search on at runtime](https://github.com/meilisearch/meilisearch/issues/3772) feature.
---
- Add the new search parameter definition
- Add related error messages
- Update OpenAPI

Define fields to search on at runtime 

---

open-api.yaml
text/0034-telemetry-policies.md
text/0060-tasks-api.md
text/0061-error-format-and-definitions.md
text/0085-api-keys.md
text/0118-search-api.md
text/0124-documents-api.md
text/0174-metrics-api.md
text/0193-experimental-features.md
text/0194-experimental-feature-api.md
text/0195-ranking-score.md
text/0246-facet-search-api.md
text/157-faceting-setting-api.md

- https://github.com/meilisearch/specifications/pull/242
- https://github.com/meilisearch/specifications/pull/246
- https://github.com/meilisearch/specifications/pull/247
- https://github.com/meilisearch/specifications/pull/248
- https://github.com/meilisearch/specifications/pull/250
- https://github.com/meilisearch/specifications/pull/251
- https://github.com/meilisearch/specifications/pull/252
- https://github.com/meilisearch/specifications/pull/253

Release v1.3.0

---

open-api.yaml
text/0034-telemetry-policies.md
text/0123-separators-settings-api.md
text/0123-settings-api.md

Allow the user to customize the list of separators used by Meilisearch to segment the documents and the queries by providing 2 new settings:
- `separatorTokens`: List of the tokens that should be considered separators
- `nonSeparatorTokens`: List of the tokens that should not be considered separators
- add a new dedicated settings spec
- update the global settings spec
- update telemetry spec

Separators settings api

---

text/0034-telemetry-policies.md
text/0119-instance-options.md
text/0262-task-queue-webhook.md

Original PRD: https://www.notion.so/meilisearch/Task-Queue-Webhook-2c9ff1c6b820489399194539d37c4d11
Introduce a configuration for a webhook url that will be called whenever a task finishes so a third party can be notified. It will be used to compute some of the required metrics for the [Monitoring Metrics v1](https://www.notion.so/Monitoring-Metrics-v1-4782d56795c043799dde33309e73a20f?pvs=21) project.
---
- The webhook URL is configured either via the env var `MEILI_TASK_WEBHOOK_URL` or via the CLI option flag `--task-webhook-url`
- By default, the webhook URL value is empty.
- If the given value does not match a valid URL format, a human-readable error is returned to the user and the engine does not start.
- A valid user-provided URL is kept as is.
- You can optionally set an …

Task queue webhook

---

open-api.yaml
text/0034-telemetry-policies.md
text/0118-search-api.md
text/0193-experimental-features.md
text/0194-experimental-feature-api.md
text/0195-ranking-score.md

---
Stabilize the `scoreDetails` feature.
---
- Remove (EXPERIMENTAL) mentions for `scoreDetails`
- Update OpenAPI with up-to-date fields
- other experimental features seem to be only partially tracked in the specs. It is not in the scope of this PR to fix this.
---
Most of the specification was written when the feature was in its experimental state. The wording should be consistent with its newly stabilized status.
---

Stabilize scoreDetails feature

---

text/0034-telemetry-policies.md

---
cf title
---
cf title
N/A
---
N/A
---

Add `gpu_enabled` to telemetry

---

text/0034-telemetry-policies.md
text/0119-instance-options.md
text/0193-experimental-features.md

See https://www.notion.so/meilisearch/Improve-debug-velocity-c756d428dd4b4716b353acde68a958cd?d=befaf62375a44c23a15e3ffe792e9dc5#66c2b0b87a1c4030a600269180c3dd81
---
- Introduce the two news logging experimental features
- Add the associated analytics

Add specification about both new logs experimental features

---

open-api.yaml
text/0034-telemetry-policies.md
text/0118-search-api.md
text/0119-instance-options.md
text/0193-experimental-features.md
text/0194-experimental-feature-api.md
text/0195-ranking-score.md

Release v1.7.0

---

text/0034-telemetry-policies.md
text/0119-instance-options.md

Implemented in https://github.com/meilisearch/meilisearch/pull/4042
Specify the new replication parameters; see https://github.com/orgs/meilisearch/discussions/725

Specify the new experimental replication parameters
